### ISSUE TITLE
the docs build on readthedocs is broken

### ISSUE THREAD

**Issue by John-Ragland** [Ocean-Data-Lab/ooipy#161]

**Comment by John-Ragland** [comment]
Added .readthedocs.toml, now I'm trying to have the release in conf.py be inherited from the version.

@lsetiawan in a recent [commit ](https://github.com/Ocean-Data-Lab/ooipy/commit/ca85cb3663f4fbb7389d9f4f92e49370247cf8d0), I'm trying to import the version from _ooipy_version.py. (the commits since have just been hard coding the release so that the docs will build again)

_ooipy_version.py is created when the package is installed, which readthedocs isn't doing in its doc build. Do you know of the best practice way to inherit the version for the docs build?

**Comment by John-Ragland** [comment]
Also, it looks like the docs build is still failing even with the hard coded release in conf.py. Here is the error from the readthedocs build. I haven't had a chance to dig into this yet.

```
Running Sphinx v7.2.6
making output directory... done

Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/ooipy/envs/latest/lib/python3.10/site-packages/sphinx/cmd/build.py", line 293, in build_main
    app = Sphinx(args.sourcedir, args.confdir, args.outputdir,
  File "/home/docs/checkouts/readthedocs.org/user_builds/ooipy/envs/latest/lib/python3.10/site-packages/sphinx/application.py", line 272, in __init__
    self._init_builder()
  File "/home/docs/checkouts/readthedocs.org/user_builds/ooipy/envs/latest/lib/python3.10/site-packages/sphinx/application.py", line 342, in _init_builder
    self.builder.init()
  File "/home/docs/checkouts/readthedocs.org/user_builds/ooipy/envs/latest/lib/python3.10/site-packages/sphinx/builders/html/__init__.py", line 219, in init
    self.init_templates()
  File "/home/docs/checkouts/readthedocs.org/user_builds/ooipy/envs/latest/lib/python3.10/site-packages/sphinx/builders/html/__init__.py", line 270, in init_templates
    self.theme = theme_factory.create(themename)
  File "/home/docs/checkouts/readthedocs.org/user_builds/ooipy/envs/latest/lib/python3.10/site-packages/sphinx/theming.py", line 227, in create
    self.load_extra_theme(name)
  File "/home/docs/checkouts/readthedocs.org/user_builds/ooipy/envs/latest/lib/python3.10/site-packages/sphinx/theming.py", line 181, in load_extra_theme
    self.load_external_theme(name)
  File "/home/docs/checkouts/readthedocs.org/user_builds/ooipy/envs/latest/lib/python3.10/site-packages/sphinx/theming.py", line 194, in load_external_theme
    theme_entry_points = entry_points(group='sphinx.html_themes')
  File "/home/docs/.asdf/installs/python/3.10.13/lib/python3.10/importlib/metadata/__init__.py", line 1021, in entry_points
    return SelectableGroups.load(eps).select(**params)
  File "/home/docs/.asdf/installs/python/3.10.13/lib/python3.10/importlib/metadata/__init__.py", line 459, in load
    ordered = sorted(eps, key=by_group)
  File "/home/docs/.asdf/installs/python/3.10.13/lib/python3.10/importlib/metadata/__init__.py", line 1018, in <genexpr>
    eps = itertools.chain.from_iterable(
  File "/home/docs/.asdf/installs/python/3.10.13/lib/python3.10/importlib/metadata/_itertools.py", line 15, in unique_everseen
    for element in iterable:
  File "/home/docs/.asdf/installs/python/3.10.13/lib/python3.10/importlib/metadata/__init__.py", line 904, in <genexpr>
    path.search(prepared) for path in map(FastPath, paths)
  File "/home/docs/.asdf/installs/python/3.10.13/lib/python3.10/importlib/metadata/__init__.py", line 802, in search
    return self.lookup(self.mtime).search(name)
  File "/home/docs/.asdf/installs/python/3.10.13/lib/python3.10/importlib/metadata/__init__.py", line 807, in mtime
    return os.stat(self.root).st_mtime
TypeError: stat: path should be string, bytes, os.PathLike or integer, not NoneType

Exception occurred:
  File "/home/docs/.asdf/installs/python/3.10.13/lib/python3.10/importlib/metadata/__init__.py", line 807, in mtime
    return os.stat(self.root).st_mtime
TypeError: stat: path should be string, bytes, os.PathLike or integer, not NoneType
The full traceback has been saved in /tmp/sphinx-err-1qlumn8n.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks!
```

**Comment by John-Ragland** [comment]
#167

**Comment by John-Ragland** [comment]
#184
